# Generated by Django 6.0.4 on 2026-05-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('master_text', models.TextField()),
                ('x_text', models.TextField(blank=True)),
                ('reddit_title', models.CharField(blank=True, max_length=300)),
                ('reddit_body', models.TextField(blank=True)),
                ('instagram_caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('posted', 'Posted'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
