# Generated by Django 6.0.4 on 2026-05-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('white_label', 'White Label'), ('kpopalypse', 'KpopalypseNow'), ('toolbox', 'ToolBox'), ('personal_brand', 'Personal Brand'), ('meme_caption', 'Meme / Edit Caption')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='instagram_status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('draft', 'Draft'), ('ready', 'Ready'), ('posted', 'Posted'), ('skipped', 'Skipped')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='reddit_status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('draft', 'Draft'), ('ready', 'Ready'), ('posted', 'Posted'), ('skipped', 'Skipped')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='x_status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('draft', 'Draft'), ('ready', 'Ready'), ('posted', 'Posted'), ('skipped', 'Skipped')], default='draft', max_length=20),
        ),
    ]
