# Generated by Django 6.0.4 on 2026-05-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_socialpost_category_socialpost_instagram_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
